---
name: Egg-Plugin-MailSend
version: 2.02
author:
  - 'Masatoshi Mizuno E<lt>lusheE<64>cpan.orgE<gt>'
abstract: Mail is delivered for Egg Plugin.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Egg::Release: 2
  Email::Valid: 0.17
  File::Which: 0.05
  Jcode: 2.06
  MIME::Entity: 5.42
  Net::SMTP: 2.3
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Egg::Plugin::MailSend:
    file: lib/Egg/Plugin/MailSend.pm
    version: 2.02
  Egg::Plugin::MailSend::CMD:
    file: lib/Egg/Plugin/MailSend/CMD.pm
    version: 2.00
  Egg::Plugin::MailSend::CMD::handler:
    file: lib/Egg/Plugin/MailSend/CMD.pm
  Egg::Plugin::MailSend::Encode::ISO2022JP:
    file: lib/Egg/Plugin/MailSend/Encode/ISO2022JP.pm
    version: 2.00
  Egg::Plugin::MailSend::SMTP:
    file: lib/Egg/Plugin/MailSend/SMTP.pm
    version: 2.00
  Egg::Plugin::MailSend::SMTP::handler:
    file: lib/Egg/Plugin/MailSend/SMTP.pm
  Egg::Plugin::MailSend::handler:
    file: lib/Egg/Plugin/MailSend.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
