abstract: Mail is delivered for Egg Plugin.
author: Masatoshi Mizuno E<lt>lusheE<64>cpan.orgE<gt>
build_requires: 
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Simple: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Egg-Plugin-MailSend
no_index: 
  directory: 
    - inc
    - t
requires: 
  Egg::Release: 2
  Email::Valid: 0.17
  File::Which: 0.05
  Jcode: 2.06
  MIME::Entity: 5.42
  Net::SMTP: 2.3
version: 2.00
